### ISSUE TITLE
#Setup Nice docu and nearly made it 😜

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#72]
@mai-soup I'm going in with a beginners mind. I.e. I follow your readme.me to the latter. I'm happy to see that it's clean, simple, and explain it's well. You're the only from the course with a proper setup 😬

I did everything you asked and still hit a snag

```
porch-reads-club-frontend-1  | Missing required API keys. Please set all required environment variables.
porch-reads-club-frontend-1 exited with code 1
```

This is my .env in the frontend and I use the same mapbox token in the backend. Backend starts normally. Frontend crashes 🫣

```
MAPBOX_TOKEN=pk.mykey

# optional - add this if you've e.g. changed the port the backend runs on
VITE_API_URL=http://localhost:3000

```

Reproducer:

1. Create a new code space
2. Create .env files with the generated keys
3. Execute the docker commands
4. Frontend complains

Regardless of the missing key, the app should at least start.

**Comment by Dr4gon** [comment]
@mai-soup I love shellscripts 😍 While reviewing your code I found the issue:

```
#!/bin/sh
if [ -z "$VITE_MAPBOX_TOKEN" ]; then
  echo "Missing required API keys. Please set all required environment variables."
  exit 1
fi

exec npm run dev
```

The `env.example` has an old variable name MAPBOX_TOKEN 🤓

**Comment by mai-soup** [comment]
> Regardless of the missing key, the app should at least start.

no can do, the mapbox sdk would make the app crash if no API key is provided even without my check. hence the instructions.

thankfully, fixing the `.env.example` is pretty easy, though.
