### ISSUE TITLE
#CleanCode No inline js and use configuration variables

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#77]
@mai-soup The thing with inline js is - just don't do it. It has so many drawbacks:

- A bad separation of concerns because the view shouldn't know about the logic 
- It's hard to read, and even harder to maintain because it's inline instead of a dynamic environment setting linked in a configuration file
- Debugging hell, if something goes wrong
- ....

`LoansView.vue`

```vue.js
// if the loan is due in 7 days or less, show a button to extend the loan
button(v-if="(new Date(loan.returnDate) - new Date()) < 1000 * 60 * 60 * 24 * 7" @click="doExtend(loan)") Extend
```

The idea here would be using a function call from JS and configure this value in your .env.

**Comment by mai-soup** [comment]
instead of environment variables, decided to assign the loan-related durations on a per-library basis (#113)
