### ISSUE TITLE
#CleanCode CreateLibraryView.vue is the brother of EditLibraryView.vue

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#78]
@mai-soup To me it seems that `CreateLibraryView.vue` is the brother of `EditLibraryView.vue`, nearly identical even, and could use a component. What's your take on this? 😁

**Comment by mai-soup** [comment]
Thanks for spotting it! I noticed it a while ago with `LibraryView.vue` and `OwnedLibraryView.vue` (#41), this one's similar, just slipped my attention.
