### ISSUE TITLE
#NamingConventions When 2 files are too close in naming that they could be the same

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#79]
@mai-soup Maybe I'm just picky with this one, but I think when `LibrariesView.vue` and `LibraryView.vue` are so close in naming, it could potentially cause confusion and wasted time on error searching in the wrong file. It's even more obvious with `BookView.vue` and `BooksView.vue`.

My recommendation here is to make the name longer/more different to make a clear naming distinction 😋

**Comment by mai-soup** [comment]
@Dr4gon I'm trying to think of a good solution for this. Would, for example, `AllLibrariesView.vue` and `SingleLibraryView.vue` be better/make sense?

**Comment by mai-soup** [comment]
(assumed that yes :eyes: )
