### ISSUE TITLE
#Patterns Interceptor for error handling in your handlers@frontend and routes@backend

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#80]
@mai-soup As a more advanced idea to handle your errors in your handlers - what a word play - use the concept of interceptors.

As illustrated here [How to implement Interceptors in JS](https://medium.com/@jscodelover/understanding-request-and-response-interceptors-in-javascript-e2fe20dbabbf#:~:text=Interceptors%20are%20useful%20because%20they,to%20modify%20the%20underlying%20code.)

It allows you to wrap an interceptor around each of your calls performing standard operations for e.g. HTTP 200 = Yeah success log and HTTP 403 = You're a naughty, naughty boy!

**Comment by Dr4gon** [comment]
@mai-soup Looking into your backend I think the routers could use an interceptor as well. The error handling makes e.g. `libraries.js` very hard to read. And I assume u haven't even implemented all the error cases.

**Comment by mai-soup** [comment]
Closing as split up into #87 and #88
