### ISSUE TITLE
Are u the backend or the frontend guy?

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#81]
@mai-soup I had quick look in your portfolio and the other projects. From what I'm able to observe you apply a similiar UI style to your projects. It may serve as your digital finger print. 

I personally like to taste different ice cone flavours to see what's out there and to be inspired by cool styled pages. I sometimes get hung upon these pages to figure out how the person did it. That maybe simply my personal preference on the frontend. 

As developers, the more we've experienced, the better our gut feeling for estimations, technolgy choices etc. 

How would u feel about changing your UI style and upgrading it with some nice shiny looking things? 

In general: Are u the backend or the frontend guy?

**Comment by mai-soup** [comment]
Thought about this a bit. To me, being a frontend guy `!==` being a visual designer (which is something I know I am not good at, no matter how cool I think it is). Most of my projects, portfolio included, had a design made by someone else (or, in the case of YelpCamp, largely default Bootstrap components) that I attempted to replicate and make work as intended. I can appreciate a nice design, but I don't particularly enjoy trying to come up with them myself.

Though, in general, I suppose I enjoy backend more.
