### ISSUE TITLE
#CleanCode Configuration variables should be set in the .env file

### ISSUE THREAD

**Issue by Dr4gon** [mai-soup/porch-reads-club#82]
@mai-soup I enjoy your comment on the calc of maxAge in

`app.js` in your backend

```js
cookie: {
      secure: process.env.NODE_ENV === 'production',
      sameSite: process.env.NODE_ENV === 'production' ? 'none' : 'lax',
      // max age of 2 weeks
      maxAge: 1000 * 60 * 60 * 24 * 14,
    },
```

I recommend extracting this to .env with a proper name to make configurable on runtime and depending on the environment this is deployed upon.

**Comment by mai-soup** [comment]
What is the purpose of making it configurable?

**Comment by mai-soup** [comment]
Closing this as stale
